version: '3'
services:
  postgres-development:
    image: postgres:11.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scrumble_development
    volumes:
      - ./data/dev:/var/lib/postgresql/data/
    ports:
      - 15432:5432
  postgres-test:
    image: postgres:11.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scrumble_test
    volumes:
      - ./data/test:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    depends_on:
      - postgres-development